version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: personal-assistant-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: personal_assistant
      POSTGRES_USER: assistant_user
      POSTGRES_PASSWORD: assistant_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - personal-assistant-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: personal-assistant-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@personalassistant.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - personal-assistant-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  personal-assistant-network:
    driver: bridge
